messages:
  help-command:
    - '&c&lUnited&f&lBrands'
    - '/brand help: shows a list of all commands'
    - '/brand create <name>: Creates a new brand with the specified name (can have multiple words)'
    - '/brand slogan <slogan>: Sets your brand''s slogan to a new slogan (multiple words supported)'
    - '/brand delete: Deletes your current brand, if it exists'
    - '/brand invite <player>: Invites a player to your brand'
    - '/brand kick <player>: Kicks a player from your brand'
    - '/brand accept: Accepts any incoming brand join requests'
    - '/brand deny: Denies any incoming brand join requests'
    - '/brand leave: Makes you leave from your current brand'
  brand-created: 'Brand <brand> has been successfully created! You can set a slogan with /brand slogan!'
  brand-deleted: 'Brand <brand> has been successfully deleted!'
  brand-cannot-be-deleted: 'You must own <brand> before deleting it!'
  brand-already-exists: 'A brand with that name already exists!'
  brand-does-not-exist: 'A brand with that name does not exist!'
  in-a-brand: 'You are member of <brand>! Leave/delete it first before making a new brand!'
  must-own-brand: 'You must own a brand to use this command!'
  must-have-brand: 'You must be in a brand to use this command!'
  must-delete-brand: 'You cannot leave <brand>! You can only delete it.'
  brand-invite: 'You were invited to join <brand>! Use /brand accept or /brand deny!'
  player-invited: 'Invite sent to player!'
  no-requests: 'You do not have any invites!'
  brand-leave: 'You left <brand>!'
  brand-join: 'You joined <brand>!'
  brand-join-sender: '<player> has joined your brand!'
  brand-deny: 'You denied &e<brand>''s invite!'
  brand-deny-sender: '<player> has denied your invite!'
  slogan-changed: 'Sucessfully changed the slogan of <brand>! It will be printed on the next bottle you brew!'
  player-kicked: 'Successfully kicked <player> from <brand>!'
  kicked-from-brand: 'You have been kicked from <brand>!'
  cannot-kick-self: 'You cannot kick yourself from <brand>!'
  cannot-invite-self: 'You cannot invite yourself to <brand>!'
  must-specify-kicked-player: 'Player argument missing! Please use /brand kick <player-name>!'
  must-specify-invited-player: 'Player argument missing! Please use /brand invite <player-name>!'
  must-specify-brand-name: 'Brand name required! Please use /brand create <brand name>, or /brand delete <brand name>'
  must-specify-slogan: 'You must specify the new slogan!'
  player-left-brand: '<player> left your brand!'
  invalid-player: 'A player with that name does not exist!'