messages:
  info-header: '&r&7&m+|✦&r&7============&r&7&l[ &c&lBrewery Info&7&l ]============&m✦|+&r'
  list-header: '&r&7&m+|✦&r&7============&r&7&l[ &c&lAll Breweries&7&l ]============&m✦|+&r'
  footer: '&r&7&m+|✦&r&7==================&m+✦+&r&7==================&m✦|+'
  help-command:
    - '&c&lUnited&f&lBreweries'
    - '/brewery help: shows a list of all commands'
    - '/brewery create <name>: Creates a new brewery with the specified name (can have multiple words)'
    - '/brewery slogan <slogan>: Sets your brewery''s slogan to a new slogan (multiple words supported)'
    - '/brewery delete: Deletes your current brewery, if it exists'
    - '/brewery invite <player>: Invites a player to your brewery'
    - '/brewery kick <player>: Kicks a player from your brewery'
    - '/brewery accept: Accepts any incoming brewery join requests'
    - '/brewery deny: Denies any incoming brewery join requests'
    - '/brewery leave: Makes you leave from your current brewery'
  help-command-admin:
    - '&c&lUnited&f&lBreweries Administration'
    - '/breweryadmin help: shows a list of all commands'
    - '/breweryadmin reload: reloads the plugin configuration'
    - '/breweryadmin clearslogan <brewery>: clears a brewery''s slogan'
    - '/breweryadmin delete <brewery>: Deletes specified brewery completely'
    - '/breweryadmin addmember <member> <brewery>: adds a member to a brewery'
    - '/breweryadmin removemember <member> <brewery>: removes a member from a brewery'
  brewery-created: 'Brewery <brewery> has been successfully created! You can set a slogan with /brewery slogan!'
  brewery-deleted: 'Brewery <brewery> has been successfully deleted!'
  brewery-cannot-be-deleted: 'You must own <brewery> before deleting it!'
  brewery-already-exists: 'A brewery with that name already exists!'
  brewery-does-not-exist: 'A brewery with that name does not exist!'
  in-a-brewery: 'You are member of <brewery>! Leave/delete it first before making a new brewery!'
  must-own-brewery: 'You must own a brewery to use this command!'
  must-have-brewery: 'You must be in a brewery to use this command!'
  must-delete-brewery: 'You cannot leave <brewery>! You can only delete it.'
  brewery-invite: 'You were invited to join <brewery>! Use /brewery accept or /brewery deny!'
  player-invited: 'Invite sent to player!'
  no-requests: 'You do not have any invites!'
  brewery-leave: 'You left <brewery>!'
  brewery-join: 'You joined <brewery>!'
  brewery-join-sender: '<player> has joined your brewery!'
  brewery-deny: 'You denied &e<brewery>''s invite!'
  brewery-deny-sender: '<player> has denied your invite!'
  slogan-changed: 'Sucessfully changed the slogan of <brewery>! It will be printed on the next bottle you brew!'
  player-kicked: 'Successfully kicked <player> from <brewery>!'
  kicked-from-brewery: 'You have been kicked from <brewery>!'
  cannot-kick-self: 'You cannot kick yourself from <brewery>!'
  cannot-invite-self: 'You cannot invite yourself to <brewery>!'
  must-specify-kicked-player: 'Player argument missing! Please use /brewery kick <player-name>!'
  must-specify-invited-player: 'Player argument missing! Please use /brewery invite <player-name>!'
  must-specify-brewery-name: 'Brewery name required! Please use /brewery create <brewery name>, or /brewery delete <brewery name>'
  must-specify-slogan: 'You must specify the new slogan!'
  max-brewery-level: 'Your brewery has reached the max level!'
  player-left-brewery: '<player> left your brewery!'
  invalid-player: 'A player with that name does not exist!'
  brewery-upgraded: '<brewery> has been upgraded to level <level>!'