messages:
  brand-created: 'Brand <brand> has been successfully created! You can set a slogan with /brand slogan!'
  brand-deleted: 'Brand <brand> has been successfully deleted!'
  brand-cannot-be-deleted: 'You must own <brand> before deleting it!'
  brand-already-exists: 'Brand <brand> already exists!'
  in-a-brand: 'You are member of <brand>! Leave/delete it first before making a new brand!'
  must-own-brand: 'You must own a brand to use this command!'
  must-have-brand: 'You must be in a brand to use this command!'
  must-delete-brand: 'You cannot leave <brand>! You can only delete it.'
  brand-invite: 'You were invited to join <brand>! Use /brand accept or /brand deny!'
  player-invited: 'Invite sent to player!'
  no-requests: 'You do not have any invites!'
  brand-leave: 'You left <brand>!'
  brand-join: 'You joined <brand>!'
  brand-join-sender: '<player> has joined your brand!'
  brand-deny: 'You denied &e<brand>''s invite!'
  brand-deny-sender: '<player> has denied your invite!'
  slogan-changed: 'Sucessfully changed the slogan of <brand>! It will be printed on the next bottle you brew!'
  player-kicked: 'Successfully kicked <player> from <brand>!'
  kicked-from-brand: 'You have been kicked from <brand>!'
  cannot-kick-self: 'You cannot kick yourself from <brand>!'
  cannot-invite-self: 'You cannot invite yourself to <brand>!'
