name: UnitedChat
version: '1.0'
main: org.unitedlands.unitedchat.UnitedChat
api-version: 1.17
authors: [ Obito17 ]
depend: [Towny, TownyChat]
softdepend: [PlaceholderAPI]
commands:
  gradient:
  cc:

