banned-worlds:
  - spawn
  - world_resource
  - world_the_end
  - world_nether
banned-commands:
  - "/maphide"
  - "/squaremap:map hide"
  - "/dungeon"
  - "/dxl"
  - "/dungeons"
  - "/pw"
  - "/playerwarp"
  - "/tfly"
commands-on-war-start:
  - "mapshow"
  - "towny war hud"
commands-on-login:
  - "mapshow"
townwar-declaration-book:
  1:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - "      <dark_red><bold>BOOK INDEX</bold></dark_red>"
    - "   <dark_gray>(Click to navigate)"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'2'>INTRO</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'4'>MECHANICS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'7'>WAR STATS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'9'>WAR REASONING</click> </bold>"
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  2:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR INTRO"
    - "  <dark_gray>Usage, Date, & Sides"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  3:
    - ""
    - "%server_time_MMMM d, Y%"
    - " "
    - "The town of <dark_red><declarer-name></dark_red> officially declared war on <dark_red><target-name></dark_red>."
    - " "
    - "The war will start as soon as <declarer-name> runs <gold>/t war declare</gold> while holding this book."
    - " "
  4:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>MECHANICS"
    - "   <dark_gray>How the war works"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  5:
    - "Each resident in both towns will get a total of three lives"
    - "When a resident is killed in the war, <gold>10 War Points</gold> go to the killing town."
    - " "
    - "If all residents of a town run out of lives, that town loses the war."
    - "<dark_gray>(More on next page)"
  6:
    - "The war will run for a total of <gold>2 days</gold> after being started. If none of the towns run out of lives, the town with the most points wins."
    - " "
    - "After the war is over, the winner will get <bold><dark_red>HALF</dark_red></bold> of the loser's town balance and bonus claims!"
  7:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR STATS"
    - "  <dark_gray>Know your enemies..."
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  8:
    - "Below are the stats of each of the towns as of writing."
    - ""
    - "<dark_red><bold><declarer-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <declarer-balance>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <declarer-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <declarer-residents>"
    - " "
    - "<dark_red><bold><target-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <target-balance>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <target-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <target-residents>"
  9:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "   <dark_red><bold>REASON & TERMS"
    - "  <dark_gray>Written by the mayor"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
nationwar-declaration-book:
  1:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - "      <dark_red><bold>BOOK INDEX</bold></dark_red>"
    - "   <dark_gray>(Click to navigate)"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'2'>INTRO</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'4'>MECHANICS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'7'>WAR STATS</click>"
    - " "
    - "<bold><color:#BEA50C>⬩<dark_red> <click:change_page:'10'>WAR REASONING</click> </bold>"
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  2:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR INTRO"
    - "  <dark_gray>Usage, Date, & Sides"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  3:
    - ""
    - "%server_time_MMMM d, Y%"
    - " "
    - "The nation of <dark_red><declarer-name></dark_red> officially declared war on <dark_red><target-name></dark_red>."
    - " "
    - "The war will start as soon as <declarer-name> runs <gold>/t war declare</gold> while holding this book."
    - " "
  4:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>MECHANICS"
    - "   <dark_gray>How the war works"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  5:
    - "Each resident in both nations will get a total of three lives"
    - "When a resident is killed in the war, <gold>10 War Points</gold> go to the killing nation."
    - " "
    - "If all residents of a town run out of lives, that town is removed from the war."
    - "<dark_gray>(More on next page)"
  6:
    - "Once all nation towns run out of lives, that nation loses the war."
    - ""
    - "The war will run for a total of <gold>5 days</gold> after being started. If none of the nations run out of lives, the nation with the most points wins."
    - "<dark_gray>(More on next page)"
  7:
    - "After the war is over, the winner will get <bold><dark_red>HALF</dark_red></bold> of the balance in all towns in a nation, and bonus claims depending on the final score!"
    - " "
    - "May the victor bring glory to their nation!"
  8:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "       <dark_red><bold>WAR STATS"
    - "  <dark_gray>Know your enemies..."
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
  9:
    - "Below are the stats of each of the nations as of writing."
    - ""
    - "<dark_red><bold><declarer-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <declarer-balance>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <declarer-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <declarer-residents>"
    - " "
    - "<dark_red><bold><target-name>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Balance: <target-balance>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Size: <target-blocks>"
    - "  <bold><color:#BEA50C>⬩<red></bold> Residents: <target-residents>"
  10:
    - "<dark_red>╔═╬<black>☠</black>╬═══╬<black>☠</black>╬═╗"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "   <dark_red><bold>REASON & TERMS"
    - "  <dark_gray>Written by the mayor"
    - ""
    - ""
    - ""
    - ""
    - ""
    - "<dark_red>╚═╬<black>☠</black>╬═══╬<black>☠</black>╬═╝"
townwar:
  delay: 1800
nationwar:
  delay: 1800
alliancewar:
  delay: 1800
townwar-declaration-name: '<color:#BEA50C>⬩ <color:#AD240C>Town War Declaration Scroll <color:#BEA50C>⬩'
nationwar-declaration-name: '<color:#BEA50C>⬩ <color:#AD240C>Nation War Declaration Scroll <color:#BEA50C>⬩'
writable-declaration-lore:
  - ''
  - '<!i><yellow>Right-click<gray> this scroll to write'
  - '<!i><gray>your reasoning behind the <yellow>war!'
  - ''
messages:
  prefix: "<bold><red>U<white>L</bold> <gray>» "
  teleport-cancelled: '<red>You have an ongoing war! You cannot teleport anywhere!'
  banned-command: '<red>You may not use this command during wars!'
  must-specify-target: '<red>No target found! Please write the target''s name in order to create a war scroll!'
  not-enough-arguments: '<red>You must specify <args>'
  mayor-offline: '<red><yellow><name></yellow> is the mayor of <yellow><warring-name></yellow> and is currently offline! You can only make an offer if they''re online!'
  not-enough-money: '<red>You have that much money in your account to offer!'
  must-have-town: '<red>You must have a town to use this command!'
  must-be-nationwar: '<red>You must be in a nation war to offer a town!'
  town-not-in-nation: '<red>You cannot offer a town that''s not part of your nation!'
  must-have-nation: '<red>You must have a nation to use this command!'
  no-wars-found: '<red>You don''t have any wars...'
  must-not-be-neutral: '<red>You cannot create a war scroll while neutral! Please disable neutrality first!'
  ongoing-war: '<red>You cannot create a new war scroll while you have an ongoing war!'
  on-cooldown: '<red>You fought too recently! You can''t declare another war yet.'
  not-enough-tokens: '<red>You cannot create a war scroll of this type! You need <cost> tokens first!'
  invalid-town-name: '<red>Town not found! Please enter the correct name!'
  invalid-declaration-book: '<red>You cannot use artifacts as war scrolls!'
  invalid-nation-name: '<red>Nation not found! Please enter the correct name!'
  must-be-mayor: '<red>Only mayors can use this command!'
  cannot-declare-on-self: '<red>You cannot declare war on your own town/nation!'
  cannot-declare-on-allies: '<red>Target is an ally! You cannot declare war on them...'
  only-mayors-can-sign: '<red>Only the mayor of <yellow><declarer-name><red> can sign this declaration book!'
  must-not-be-neutral-target: '<red>Target is neutral! You can only create scrolls for non-neutral enemies!'
  must-have-online-player: '<red>Your target must have at least 1 player online to declare a war!'
  must-declare-nationwar: '<red>You cannot declare a <yellow>town war</yellow> because both sides have nations! Declare a <yellow>nation war</yellow> instead!'
  ongoing-war-target: '<red>Target has an ongoing war! You cannot declare war on them!'
  invalid-held-book: '<red>You must be holding a <yellow>declaration scroll</yellow> to use this command'
  must-be-book-owner: '<red>Your town is not the owner of this declaration scroll!'
  war-won: '<green>Victory! The war has ended! You''ve won <bold><gold><money-amount></gold></bold> Gold from your enemy''s balance, and an extra <bonus-claims> bonus claims!'
  war-lost: '<red>You''ve lost the war... Your enemy has taken over <bold><gold><money-amount></gold></bold> Gold from your total balance, and they''ve earned <bonus-claims> bonus claims from you.'
  player-killed: '<red><killer> killed <victim>! <victim-warrer> has lost <dark_red>5 health</dark_red> permanently!'
  totem-pop: '<red><victim> has popped a totem! <victim-warrer> lost 1 hp!'
  removed-from-war: '<red><victim> has lost all their lives for the day, and has been removed from the war!'
  no-pending-requests: '<red>You don''t have any pending surrender requests!'
  won-surrender-money: '<green>War won! You''ve earned <gold><money></gold> Gold in your town/nation balance!'
  lost-surrender-money: '<red>You''ve surrendered from the war... Your side has offered <gold><money> Gold</gold>, and the deal was accepted.'
  won-surrender-town: '<green>Victory! You''ve won the war, and accepted <yellow><town></yellow> as a surrender offer from your enemy. It is now a part of your nation!'
  lost-surrender-town: '<red>You''ve surrendered from the war... Your side has offered all of <yellow><town></yellow> to end the war, and the deal was accepted.'
  war-end-peace: '<green>The war has ended... Both sides agreed on a White Peace offer.'
  war-end-tie: '<green>The war has ended... Neither side won as they both reached 0 HP!'
  surrender-received: '<red>You received a surrender request from <yellow><requester></yellow>! They have offered <yellow><offer></yellow> in order to end this war! Do <yellow>/surrender accept</yellow> to accept!'
  request-sent: '<green>Surrender request successfully sent! You must now wait for the other side to accept or decline it!'
  health-too-high-to-surrender: '<red>You cannot surrender right now! Your health must be lower than or equal to <gold>65 HP</gold>!'
  town-deleted-removed-from-war: '<red>Your town was deleted! You''ve been removed from the war and lost all your lives!'
  # Doesn't go through minimessage.
  cannot-do-in-war: '§cYou cannot use this command while in a war.'
  town-purchased-declaration: '§bYour town has just purchased a declaration of war!'
  nation-purchased-declaration: '§bYour nation has just purchased a declaration of war!'
  war-confirmation: '§cAre you sure you want to create a §e<type>§c scroll? This will cost you §e<cost> War tokens§c!'
  war-declare-confirmation: '§cAre you sure you want to declare a §e<type>§c on §e<target>? §cThe war will start immediately after confirmation.'
  surrender-confirm: '§cAre you sure you want to send a surrender request to §e<warring-name>§c? You will lose the war if the request is accepted.'
  surrender-accept-money: '§cAre you sure you want to accept §6<money-amount> Gold§c from §e<surrender-name>§c? Accepting will end the war immediately with you as a winner.'
  surrender-accept-town: '§cAre you sure you want to accept §e<offered-town>§c from §e<surrender-name>§c? Accepting will end the war immediately with you as a winner, and §e<offered-town>§c will become part of your nation.'
  surrender-accept-whitepeace: '§cAre you sure you want to accept the §eWhite Peace§c from §e<surrender-name>§c? Accepting will end the war immediately with you as a winner, however, neither side loses or gains anything.'