base-chances:
  exposure-therapy:
    1: 10
    2: 20
    3: 30
  expert-harvester:
    1: 10
    2: 20
    3: 30
  fertiliser:
    1: 10
    2: 15
    3: 20
  green-thumb:
    1: 40
    2: 50
    3: 60
  fortunate:
    1: 10
    2: 20
    3: 30
  self-reflection:
    1: 10
    2: 20
    3: 30
  counter-attack:
    1: 5
    2: 10
    3: 15
  retriever:
    1: 20
    2: 40
    3: 60
  piercing:
    1: 20
    2: 40
    3: 60
  stun:
    1: 5
    2: 10
    3: 15
  critical-hit:
    1: 5
    2: 10
    3: 15
  lucky-catch:
    1: 20
    2: 30
    3: 40
  pescatarian:
    1: 100
    2: 100
  hooked:
    1: 100
    2: 100
    3: 100
  reforestation:
    1: 35
    2: 65
    3: 100
  precision-cutting:
    1: 10
    2: 20
    3: 30
  excavator:
    1: 10
    2: 20
    3: 30
cooldowns:
  green-thumb:
    1: 300
    2: 270
    3: 240
  frenzy:
    1: 300
    2: 270
    3: 240
  fortification:
    1: 300
    2: 270
    3: 240
  blast-mining:
    1: 300
    2: 270
    3: 240
  precision-strike:
    1: 60
    2: 50
    3: 40
  focus:
    1: 300
    2: 270
    3: 240
  grapple:
    1: 300
    2: 270
    3: 1
  tree-feller:
    1: 300
    2: 270
    3: 1
  tunneller:
    1: 300
    2: 270
    3: 1
  refiner:
    1: 300
    2: 270
    3: 1
durations:
  green-thumb:
    1: 40
    2: 50
    3: 60
  frenzy:
    1: 10
    2: 15
    3: 20
  blast-mining:
    1: 10
    2: 15
    3: 20
  fortification:
    1: 10
    2: 20
    3: 30
  precision-strike:
    1: 3
    2: 5
    3: 8
  focus:
    1: 5
    2: 10
    3: 15
  grapple:
    1: 5
    2: 10
    3: 15
  tree-feller:
    1: 10
    2: 20
    3: 30
  tunneller:
    1: 10
    2: 20
    3: 30
  refiner:
    1: 40
    2: 50
    3: 60
fortification-effects:
  1:
    - HUNGER
    - LUCK
    - JUMP
  2:
    - SPEED
    - SLOW
    - INSTANT_DAMAGE
  3:
    - POISON
    - SLOW_DIGGING
    - FAST_DIGGING
    - ABSORPTION
brewing-items:
  - FERMENTED_SPIDER_EYE
  - RABBIT_FOOT
  - BLAZE_POWDER
  - MAGMA_CREAM
  - GHAST_TEAR
  - NETHER_WART
  - GLOWSTONE_DUST
  - SPIDER_EYE
  - GOLDEN_CARROT
  - GLISTERING_MELON
  - PUFFERFISH
plant-foods:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - COOKIE
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - DRIED_KELP
  - MELON_SLICE
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - GLOW_BERRIES
crop-names:
  - WHEAT
  - CARROTS
  - COCOA
  - BEETROOTS
  - POTATOES
  - MELON
  - PUMPKIN
  - NETHER_WART
potions:
  NIGHT_VISION:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  INVISIBILITY:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  JUMP:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  FIRE_RESISTANCE:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  SPEED:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  SLOWNESS:
    default: 90
    extended: 240
    upgraded: 20
    max_amplifier: 3
  WATER_BREATHING:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  POISON:
    default: 45
    extended: 90
    upgraded: 21
    max_amplifier: 1
  REGEN:
    default: 45
    extended: 90
    upgraded: 22
    max_amplifier: 1
  STRENGTH:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  WEAKNESS:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  LUCK:
    default: 300
    extended: 300
    upgraded: 300
    max_amplifier: 0
  SLOW_FALLING:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  INSTANT_HEAL:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
  INSTANT_DAMAGE:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
wrangler-mobs:
  - PIG
  - COW
  - CHICKEN
  - HORSE
  - SHEEP
  - AXOLOTL
  - BAT
  - BEE
  - CAT
  - DOLPHIN
  - DONKEY
  - FOX
  - GLOW_SQUID
  - GOAT
  - LLAMA
  - MOOSHROOM
  - MULE
  - OCELOT
  - PANDA
  - PARROT
  - POLAR_BEAR
  - RABBIT
  - SQUID
  - STRIDER
  - TRADER_LLAMA
  - TURTLE
  - WOLF
trafficker-mobs:
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - SPIDER
  - ENDERMAN
  - ENDERMITE
  - GHAST
  - GUARDIAN
  - HOGLIN
  - HUSK
  - MAGMA_CUBE
  - PHANTOM
  - PIGLIN
  - PIGLIN_BRUTE
  - SILVERFISH
  - SKELETON
  - SLIME
  - SPIDER
  - STRAY
  - VEX
  - WITCH
  - WITHER
  - ZOGLIN
  - ZOMBIE
  - ZOMBIFIED_PIGLIN
archaeologist-loot:
  diamond:
    material: DIAMOND
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  emerald:
    material: EMERALD
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  turtle_egg:
    material: TURTLE_EGG
    chance: 0.01
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SAND
  raw_gold:
    material: RAW_GOLD
    chance: 0.03
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_gold2:
    material: RAW_GOLD
    chance: 0.03
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
    blocks:
      - GRAVEL
  gunpowder:
    material: GUNPOWDER
    chance: 0.01
    min: 2
    max: 6
    required-level: 3
    level-modifier: 0.0
    blocks:
      - GRAVEL
  nautilus_shell:
    material: NAUTILUS_SHELL
    chance: 0.03
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - CLAY
  wither_skull:
    material: WITHER_SKELETON_SKULL
    chance: 0.001
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  corals:
    materials:
      - TUBE_CORAL
      - BRAIN_CORAL
      - BUBBLE_CORAL
      - FIRE_CORAL
      - HORN_CORAL
    chance: 0.01
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SAND
  magma_cream:
    material: MAGMA_CREAM
    chance: 0.01
    min: 1
    max: 3
    required-level: 3
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  lapis:
    material: LAPIS_LAZULI
    chance: 0.01
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  scute:
    material: SCUTE
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.01
    blocks:
      - SAND
  gold_ingot:
    material: GOLD_INGOT
    chance: 0.01
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_copper:
    material: RAW_COPPER
    chance: 0.03
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - GRAVEL
  brick:
    material: BRICK
    chance: 0.03
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - GRAVEL
  prismarine_crystal:
    material: PRISMARINE_CRYSTAL
    chance: 0.05
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - CLAY
  gold_nugget2:
    material: GOLD_NUGGET
    chance: 0.05
    min: 1
    max: 4
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  blaze_rod:
    material: BLAZE_ROD
    chance: 0.03
    min: 1
    max: 2
    required-level: 2
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  coal:
    material: COAL
    chance: 0.01 # 1%
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  charcoal:
    material: CHARCOAL
    chance: 0.01 # 1%
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS_BLOCK
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  gold_nuggets:
    material: GOLD_NUGGET
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - RED_SAND
  raw_iron:
    material: RAW_IRON
    chance: 0.03
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - GRAVEL
  prismarine_shard:
    material: PRISMARINE_SHARD
    chance: 0.05
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    blocks:
      - CLAY
  quartz:
    material: QUARTZ
    chance: 0.05
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  glowstone_dust:
    material: GLOWSTONE_DUST
    chance: 0.05
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  red_mushroom:
    material: RED_MUSHROOM
    chance: 0.05
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - MYCELIUM
  brown_mushroom:
    material: BROWN_MUSHROOM
    chance: 0.05
    min: 1
    max: 2
    required-level: 1
    level-modifier: 0.0
    blocks:
      - MYCELIUM
mineral-finder-loot:
  maronine:
    material: GOLD_NUGGET
    name: "<!i><color:#800000>Maronine Nugget"
    min: 1
    max: 1
    lore:
      - "<white>"
      - "<!i><grey>Can be used to craft <color:#800000>Maronine Ingots"
      - "<white>"
    chance: 0.005
    required-level: 1
    level-modifier: 0.0
    custom-model-data: 1
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
  litnium:
    material: GOLD_NUGGET
    chance: 0.005
    min: 1
    max: 2
    required-level: 2
    custom-model-data: 2
    name: "<!i><color:#14C183>Litnium Nugget"
    lore:
      - "<white>"
      - "<!i><grey>Can be used to craft <color:#14C183>Litnium Ingots"
      - "<white>"
    level-modifier: 0.0
    blocks:
      - DIRT
      - ROOTED_DIRT
      - GRASS
      - PODZOL
      - COARSE_DIRT
      - FARMLAND
  cinnarite:
    material: GOLD_NUGGET
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    custom-model-data: 3
    name: "<!i><color:#F3F29E>Cinnarite Nugget"
    lore:
      - "<white>"
      - "<!i><grey>Can be used to craft <color:#F3F29E>Cinnarite Ingots"
      - "<white>"
    level-modifier: 0.0
    blocks:
      - SAND
      - RED_SAND
rare-catch-loot:
  riverfish:
    name: "<!i><color:#2DB5D0>River Fish"
    lore:
      - "<white>"
      - "<!i><white>Can be used to extract <color:#2DB5D0>rare oils"
      - "<white>"
    material: COD
    chance: 0.05
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
    custom-model-data: 1
    biomes:
      - RIVER
  shimmerfish:
    name: "<!i><color:#F0B32A>Shimmer Fish"
    lore:
      - "<white>"
      - "<!i><white>Can be used to extract <color:#F0B32A>rare oils"
      - "<white>"
    material: COD
    chance: 0.05
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    custom-model-data: 2
    biomes:
      - WARM_OCEAN
  icefish:
    name: "<!i><color:#2761C8>Ice Fish"
    lore:
      - "<white>"
      - "<!i><white>Can be used to extract <color:#2761C8>rare oils"
      - "<white>"
    material: COD
    chance: 0.05
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    custom-model-data: 3
    biomes:
      - FROZEN_OCEAN
      - FROZEN_RIVER
      - DEEP_FROZEN_OCEAN
treasure-hunter-loot:
  prismarine_crystal:
    material: PRISMARINE_CRYSTAL
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  quartz:
    material: QUARTZ
    chance: 0.01
    min: 1
    max: 4
    required-level: 3
    level-modifier: 0.0
  diamond:
    material: DIAMOND
    chance: 0.01
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  emerald:
    material: EMERALD
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  ender_pearl:
    material: ENDER_PEARL
    chance: 0.02
    min: 1
    max: 2
    required-level: 3
    level-modifier: 0.0
  netherite_stuff:
    materials:
      - NETHERITE_HELMET
      - NETHERITE_CHESTPLATE
      - NETHERITE_BOOTS
      - NETHERITE_LEGGINGS
      - NETHERITE_SWORD
      - NETHERITE_AXE
      - NETHERITE_HOE
      - NETHERITE_SHOVEL
      - NETHERITE_PICKAXE
    chance: 0.005
    min: 1
    max: 1
    required-level: 3
    level-modifier: 0.0
    random-damage: true
  gold_ingot:
    material: GOLD_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  prismarine_shard:
    material: PRISMARINE_SHARD
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  corals:
    materials:
      - TUBE_CORAL
      - BRAIN_CORAL
      - BUBBLE_CORAL
      - FIRE_CORAL
      - HORN_CORAL
    chance: 0.03
    min: 1
    max: 3
    required-level: 2
    level-modifier: 0.0
  heart_of_the_sea:
    material: HEART_OF_THE_SEA
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
  diamond_stuff:
    materials:
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_BOOTS
      - DIAMOND_LEGGINGS
      - DIAMOND_SWORD
      - DIAMOND_AXE
      - DIAMOND_HOE
      - DIAMOND_SHOVEL
      - DIAMOND_PICKAXE
    chance: 0.01
    min: 1
    max: 1
    required-level: 2
    level-modifier: 0.0
    random-damage: true
  lapis:
    material: LAPIS_LAZULI
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.01
  iron_ingot:
    material: IRON_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  copper_ingot:
    material: COPPER_INGOT
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  coal:
    material: COAL
    chance: 0.03
    min: 1
    max: 3
    required-level: 1
    level-modifier: 0.0
  nautilus_shell:
    material: NAUTILUS_SHELL
    chance: 0.04
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.01
  disks:
    chance: 0.01
    materials:
      - MUSIC_DISK_13
      - MUSIC_DISK_CAT
      - MUSIC_DISK_BLOCKS
      - MUSIC_DISK_CHIRP
      - MUSIC_DISK_FAR
      - MUSIC_DISK_MALL
      - MUSIC_DISK_MELLOHI
      - MUSIC_DISK_STAL
      - MUSIC_DISK_STRAD
      - MUSIC_DISK_WARD
      - MUSIC_DISK_11
      - MUSIC_DISK_WAIT
      - MUSIC_DISK_OTHERSIDE
      - MUSIC_DISK_PIGSTEP
    min: 1
    max: 1
    required-level: 1
    level-modifier: 0.0
messages:
  no-permission: "You do not have permission to execute this command!"
  must-be-hunter: "<red>You must be a hunter with the <yellow>Trafficker Skill<red> to use this safari net on this entity!"
  must-be-farmer: "<red>You must be a farmer with the <yellow>Wrangler Skill<red> to use this safari net on this entity!"
  points-usage: "<red>/points add/remove <player> <job name> <amount>"
  points-added: "<green>Successfully added points to player!"
  points-removed: "<green>Successfully removed points from player!"