base-chances:
  exposure-therapy:
    1: 10
    2: 20
    3: 30
  expert-harvester:
    1: 10
    2: 20
    3: 30
  fertiliser:
    1: 10
    2: 15
    3: 20
  green-thumb:
    1: 40
    2: 50
    3: 60
  fortunate:
    1: 10
    2: 20
    3: 30
  self-reflection:
    1: 10
    2: 20
    3: 30
  counter-attack:
    1: 5
    2: 10
    3: 15
  retriever:
    1: 20
    2: 40
    3: 60
  piercing:
    1: 20
    2: 40
    3: 60
  stun:
    1: 5
    2: 10
    3: 15
  critical-hit:
    1: 5
    2: 10
    3: 15
  lucky-catch:
    1: 20
    2: 30
    3: 40
  pescatarian:
    1: 100
    2: 100
  hooked:
    1: 100
    2: 100
    3: 100
  reforestation:
    1: 35
    2: 65
    3: 100
  precision-cutting:
    1: 10
    2: 20
    3: 30
  excavator:
    1: 10
    2: 20
    3: 30
cooldowns:
  green-thumb:
    1: 300
    2: 270
    3: 240
  frenzy:
    1: 300
    2: 270
    3: 240
  fortification:
    1: 300
    2: 270
    3: 240
  blast-mining:
    1: 300
    2: 270
    3: 240
  precision-strike:
    1: 60
    2: 50
    3: 40
  focus:
    1: 300
    2: 270
    3: 240
  grapple:
    1: 300
    2: 270
    3: 1
  tree-feller:
    1: 300
    2: 270
    3: 1
  tunneller:
    1: 300
    2: 270
    3: 1
  refiner:
    1: 300
    2: 270
    3: 1
durations:
  green-thumb:
    1: 40
    2: 50
    3: 60
  frenzy:
    1: 10
    2: 15
    3: 20
  blast-mining:
    1: 10
    2: 15
    3: 20
  fortification:
    1: 10
    2: 20
    3: 30
  precision-strike:
    1: 3
    2: 5
    3: 8
  focus:
    1: 5
    2: 10
    3: 15
  grapple:
    1: 5
    2: 10
    3: 15
  tree-feller:
    1: 10
    2: 20
    3: 30
  tunneller:
    1: 10
    2: 20
    3: 30
  refiner:
    1: 40
    2: 50
    3: 60
fortification-effects:
  1:
  - HUNGER
  - LUCK
  - JUMP
  2:
  - SPEED
  - SLOW
  - INSTANT_DAMAGE
  3:
  - POISON
  - SLOW_DIGGING
  - FAST_DIGGING
  - ABSORPTION
brewing-items:
  - FERMENTED_SPIDER_EYE
  - RABBIT_FOOT
  - BLAZE_POWDER
  - MAGMA_CREAM
  - GHAST_TEAR
  - NETHER_WART
  - GLOWSTONE_DUST
  - SPIDER_EYE
  - GOLDEN_CARROT
  - GLISTERING_MELON
  - PUFFERFISH
plant-foods:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - COOKIE
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - DRIED_KELP
  - MELON_SLICE
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - GLOW_BERRIES
crop-names:
  - WHEAT
  - CARROTS
  - COCOA
  - BEETROOTS
  - POTATOES
  - MELON
  - PUMPKIN
  - NETHER_WART
potions:
  NIGHT_VISION:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  INVISIBILITY:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  JUMP:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  FIRE_RESISTANCE:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  SPEED:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  SLOWNESS:
    default: 90
    extended: 240
    upgraded: 20
    max_amplifier: 3
  WATER_BREATHING:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  POISON:
    default: 45
    extended: 90
    upgraded: 21
    max_amplifier: 1
  REGEN:
    default: 45
    extended: 90
    upgraded: 22
    max_amplifier: 1
  STRENGTH:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  WEAKNESS:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  LUCK:
    default: 300
    extended: 300
    upgraded: 300
    max_amplifier: 0
  SLOW_FALLING:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  INSTANT_HEAL:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
  INSTANT_DAMAGE:
    default: 0
    extended: 0
    upgraded: 0
    max_amplifier: 1
archaeologist-loot:
  nether_star: # name can be whatever here.
    material: NETHER_STAR
    chance: 0.01 # 1%
    amount-range: 1-5
    required-level: 1
    level-modifier: 0.05 # increases the chance by 5% for each level.
    blocks:
      - SOUL_SAND
      - SOUL_SOIL
      - DIRT
treasure-hunter-loot:
  nether_star: # name can be whatever here.
    material: NETHER_STAR
    chance: 1.0
    amount-range: 1-5
    required-level: 1
    level-modifier: 0.05 # increases the chance by 5% for each level.
messages:
  no-permission: "You do not have permission to execute this command!"