base-chances:
  exposure-therapy:
    1: 10
    2: 20
    3: 30
  expert-harvester:
    1: 10
    2: 20
    3: 30
  fertiliser:
    1: 10
    2: 15
    3: 20
  green-thumb:
    1: 40
    2: 50
    3: 60
  fortunate:
    1: 10
    2: 20
    3: 30
cooldowns:
  green-thumb:
    1: 300
    2: 270
    3: 240
  frenzy:
    1: 300
    2: 270
    3: 240
  blast-mining:
    1: 300
    2: 270
    3: 240
durations:
  green-thumb:
    1: 40
    2: 50
    3: 60
  frenzy:
    1: 10
    2: 15
    3: 20
  blast-mining:
    1: 10
    2: 15
    3: 20
plant-foods:
  - APPLE
  - MUSHROOM_STEW
  - BREAD
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - DRIED_KELP
  - MELON_SLICE
  - CARROT
  - POTATO
  - BAKED_POTATO
  - POISONOUS_POTATO
  - PUMPKIN_PIE
  - BEETROOT
  - BEETROOT_SOUP
  - SWEET_BERRIES
  - GLOW_BERRIES
crop-names:
  - WHEAT
  - CARROTS
  - BEETROOTS
  - POTATOES
  - MELON
  - PUMPKIN
  - NETHER_WART
potions:
  NIGHT_VISION:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  INVISIBILITY:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  JUMP:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  FIRE_RESISTANCE:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  SPEED:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  SLOW:
    default: 90
    extended: 240
    upgraded: 20
    max_amplifier: 3
  WATER_BREATHING:
    default: 180
    extended: 480
    upgraded: 180
    max_amplifier: 0
  POISON:
    default: 45
    extended: 90
    upgraded: 21
    max_amplifier: 1
  REGENERATION:
    default: 45
    extended: 90
    upgraded: 22
    max_amplifier: 1
  STRENGTH:
    default: 180
    extended: 480
    upgraded: 90
    max_amplifier: 1
  WEAKNESS:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
  LUCK:
    default: 300
    extended: 300
    upgraded: 300
    max_amplifier: 0
  SLOW_FALLING:
    default: 90
    extended: 240
    upgraded: 90
    max_amplifier: 0
messages:
  no-permission: "You do not have permission to execute this command!"