messages:
  prefix: "<bold><red>U<white>L</bold> <dark_gray>» "
  help-message:
    - '<bold><red>United<white>PvP'
    - '<red>/pvp degrade on/off - <gray> Toggle hostility decrease every new Towny day'
    - '<red>/pvp status - <gray>Show your current status and hostility points.'
  in-combat: '<red>You can''t use that command while in combat.'
  pvp-disabled: '<red>PvP disabled.'
  no-permission: '<red>No permission!'
  pvp-enabled: '<red>PvP enabled.'
  pvp-degrade-enabled: '<green>Your hostility will now decrease every new towny day!'
  pvp-degrade-disabled: '<red>Your hostility will now never decrease.'
  player-not-recognized: '<red>Player not found'
  pvp-status: '<red>Your current status is <yellow><status><red>, and you have <yellow><hostility> Hostility points.'

hostility-color-stages:
  0: '#E6850B'
  1: '#19B80B'
  2: '#EE7878'
  3: '#EE7878'
  4: '#EE7878'
  5: '#EE7878'
  6: '#EE7878'
  7: '#EE7878'
  8: '#EF6A6A'
  9: '#EF5959'
  10: '#EF4949'
  11: '#E73B3B'
  12: '#E73B3B'
  13: '#E73B3B'
  14: '#CF2929'
  15: '#CF2929'
  16: '#B12323'
  17: '#982020'
  18: '#861D1D'
  19: '#6E1717'
  20: '#541111'
  21: '#360B0B'