name: UnitedPvP
version: '${project.version}'
main: org.unitedlands.unitedpvp.UnitedPvP
api-version: 1.17
authors: [ Obito17 ]
depend: [ CombatLogX, Towny, TownyChat, UnitedCore ]
softdepend: [ PlaceholderAPI ]
commands:
  pvp:
  fftown:
  ffnation:
  tadmin:
